### PR TITLE
add redis-py 4.x support

### PR DESCRIPTION
**Pull request by lionelnicolas**
This introduces redis-py 4.x support.

The only unit tests which were failing after upgrading redis-py to 4.1.0 were the `GeoDB` ones, because of parameter changes in `geoadd`.

I used `parse_version` to get backward compatibility with redis-py 3.x, but we could also simply remove 3.x support. I also bumped minimal 3.x version to 3.5.0 because of `hset` compatibility issues with lower versions:

```
#~ python -m unittest tests/test_*
.............s.....................E.............................................................................................................................................................
======================================================================
ERROR: test_hmset (tests.test_dicts.DictTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/user/src/redis-collections/tests/test_dicts.py", line 439, in test_hmset
    d.update({1: 2, 3: 4})
  File "/home/user/src/redis-collections/redis_collections/dicts.py", line 348, in update
    self._update_helper(other)
  File "/home/user/src/redis-collections/redis_collections/dicts.py", line 332, in _update_helper
    self._transaction(_update_helper_trans)
  File "/home/user/src/redis-collections/redis_collections/base.py", line 230, in _transaction
    self.redis.transaction(trans, self.key, *extra_keys)
  File "/home/user/src/redis-collections/.venv/lib/python3.9/site-packages/redis/client.py", line 781, in transaction
    func_value = func(pipe)
  File "/home/user/src/redis-collections/redis_collections/base.py", line 228, in trans
    results.append(fn(pipe))
  File "/home/user/src/redis-collections/redis_collections/dicts.py", line 327, in _update_helper_trans
    self._hmset(pickled_data, pipe=pipe)
  File "/home/user/src/redis-collections/redis_collections/base.py", line 167, in _hmset
    return cmd(self.key, mapping=mapping)
TypeError: hset() got an unexpected keyword argument 'mapping'

----------------------------------------------------------------------
Ran 193 tests in 1.338s

FAILED (errors=1, skipped=1)
```

### CODE REVIEW

**Comment by lionelnicolas** [comment]
Hi @bbayles !

Is is possible to trigger CI workflow ?

Thanks.

**Comment by honzajavorek** [comment]
Hi, I'm a zombie maintainer here and I won't do anything about the PR, but I at least triggered the builds 😀

**Comment by lionelnicolas** [comment]
> Hi, I'm a zombie maintainer here and I won't do anything about the PR, but I at least triggered the builds grinning

Haha ok thanks !

**Comment by bbayles** [comment]
Working on it!

**Comment by bbayles** [comment]
I've pushed a new version to PyPI. Thanks!

**Comment by lionelnicolas** [comment]
Thanks !

**Pull request closed without merging**
